image: node:latest

# Pipeline
stages:
  - install
  - build
  - test

variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
   CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
   key:
     files:
        - package.json
   paths:
      - .npm
      - cache/Cypress
      - node_modules


# Jobs 
install_dependencies:
  stage: install
  script:
    - npm ci --cache .npm --prefer-offline
    - npm install -g serve
  artifacts:
    paths:
      - node_modules/

bundle_app:
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - build/

e2etest:
# Node docker image with Cypress and Chrome pre-installed 
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  only:
    - main
  script:
#Runs serve to deploy build
    - echo "Run tests in headless mode"
    - serve -s build &
    - npm run start:ci
    - kill %1